### PR TITLE
Snooty

### PR DESCRIPTION
**Pull request by tom7**
Switch from the ancient and unmaintainable "snoot.org px10" to the new "DFX Snooty 10px", which is basically the same font but generated using a modern approach and with missing characters like infinity, plus/minus.

### CODE REVIEW

**Comment by sophiapoirier** [comment]
This looks and works great overall for me! I updated the Mac Xcode projects (btw the hashes in there seem unrelated to filename or contents or anything, so I've always found it safe to just search/replace filenames that change) and removed some "font tweaks" stuff no longer necessary. I also refactored some of that logic as the questions basically now come down to: are you a bitmap font? and: are you Snooty? and so I simplified those two paths.

The snoot.org workarounds are so old that I lost track of which were definitely necessary and which maybe weren't but then got baked into the layout of our GUIs.  The specifically the workaround to offset right-aligned text by two pixels seems to be one of those, and with the addition of the infinity character, this was no longer benign because in Skidder it actually caused that character (presumably due to being wider?) to truncate. So removing that tweak then required me to adjust the right-edge-placement of all right-aligned Snooty text by two pixels to restore them back to how they were positioned before. I took screen shots before and after the changes and it all lines up for me, but it might not be the case for you because that tweak only ever was present for macOS (potentially erroneously so). However, at least for me, the results both look the same as before and also match the original mockup designs.  I've attached an example with left and right-aligned text (Scrubby) that perhaps you can compare to and see how much the layout / alignment-edges match for you on Windows?

scrubby-snooty

I also found this version of the font to render with occasionally a pixel of more space between two characters (in a good way; comparably the places where this happens looked a little squashed together with snoot.org px10). For that reason, I had to re-layout some of the help box text and even truncate the "units" label on Skidder's rate (sync) parameter.

Do to some of these changes surely impacting the Windows side visually too, I won't merge this yet and will leave it to you to take a look and see whether you experience any issues after my changes?

**Review by sophiapoirier — APPROVED** [review]

**Comment by tom7** [comment]
Yeah, I changed the letter spacing to make it a bit more consistent, so that's expected. Glad you think it looks better!
In your screenshot: Did you notice that the descenders (on g and y) are cut off in the help? Looks like the text is one or two pixels higher in the current UI (origin/main) on windows. Maybe one is enough to fit them in there.

**Comment by sophiapoirier** [comment]
Huh good catch, and I think I've fixed it with latest push?

scrubby-snooty

**Comment by tom7** [comment]
It looks great in your screenshot. For me, the text is one or two pixels too low, and for some reason the textarea.Offset(0, -2) thing from tweaks ends up cutting off the top of the text. I think this is overall still an improvement over the old unmaintainable font, though, so left a TODO in there and I'm gonna merge it.

**Pull request merged**
