### PR TITLE
site: add Transverb presets by Styrofoam for AU + VST

### PR DESCRIPTION
**Pull request by sophiapoirier**
These Transverb presets by the musician Styrofoam used to be posted on the now-deceased Audio Units page.  I finally got around to converting them to VST preset files (a practical application for settings copy'n'paste) and thought to add them as a download in the Transverb box on the main page.  Perhaps you might have opinions about that in itself?  Or about a different/better icon for the download link than the knobs emoji?  Or different layout?

### CODE REVIEW

**Comment by tom7** [comment]
This seems fine to me. I don't have a strong opinion about it. Some thoughts:
 - I would guess that not a lot of people want to deal with downloading a separate preset file and installing it, but maybe I'm just projecting.
 - If we do end up getting more contributed presets, I think having a single download for all of them (per-plugin) is a good way to scale. If that seems desirable, we could welcome contributions, I guess.
 - If we're unlikely to have a lot of presets, I could also imagine that we just bake them (or the best ones, according to our extremely refined ear-tastes) directly into the plugins, which is most convenient for users, if least-scalable.

Icon looks good to me. I have in mind that we should redo these icons at some point, probably to make it clearer which is the "right" download for mac/windows, and relegate some of the extended options to less prominent position.

**Comment by sophiapoirier** [comment]
Interesting thoughts...  Yeah I think I probably wouldn't be likely to do a separate download either.  I've moved to installers for Mac, though, and have a script that automatically generates it, so would be just slightly annoying to have to interrupt the automation and manually pack in the presets... enough to probably just prevent me from doing it (and remembering each time when releasing any update).

After 20 years, these are the only preset contributions we have ever received, so I kinda doubt that will become "a thing", but maybe I'm wrong.  Maybe I will just give a listen sometime and pick a few favorites out and bake them into the built-in presets, that's a fine notion.

Otherwise sprucing up the download icons sometime sounds good to me too.  I know I made the documentation one and it certainly sux.  Regarding differentiation of the plug downloads, my thought is to make it just Mac and Windows moving forwards.  I've done that since posting the RMS Buddy AU update, for example.  No more AU icon separate from Mac, no more classic Mac OS (the old Macintosh computer icon, cute as it is) option, just current macOS builds, relegating the old to the museum.  They could still be updated too, of course, but my intention is to stop proliferating multiple Mac downloads and just have one for each plugin.

**Comment by sophiapoirier** [comment]
Alright taking your suggestions, in 7dec54 I chose four out of the nine presets to make built-in, and then I basically undid everything in this PR to remove the separate presets download.  It turns out two of the presets were identical, and another two were nearly identical (one had TOMSOUND enabled and the other disabled), leaving more like seven distinct presets, and I kept four.  Though if your preeminently golden ears have other opinions about keepers, happy to change the selection.

**Comment by tom7** [comment]
Good on all counts! I feel like our plugins don't have quite enough presets today, so it's nice to round them out, but good to be selective.
We're on the same page about icons. For windows I expect to just publish the 64-bit VSTs and relegate the 32s to the museum (and probably not update them any more). The DOS icon is funny to me, but in 2020 it's probably actually a lot more confusing than the joke is worth! So I'm imagining something like just a "flat" windows squares icon and apple logo (or X?).

**Comment by sophiapoirier** [comment]
Yeah makes sense to perhaps make the Windows icon recognizable to these young'uns who grew up with smart phones.  I would tend to think that the Mac/Finder face (like what we use now) is the most common and recognizable symbol for a Mac download.  Apple logo is maybe ambiguous in that there is 3rd party software for iOS/tvOS/watchOS too, though on the other hand you can't download those from websites.  X is definitely dead as its been dropped from any OS name for some years now and we have now officially superseded its roman numerical meaning as of a couple of months ago having reached macOS 11.

**Pull request merged**
