### PR TITLE
New UI and visualization for Buffer Override

### PR DESCRIPTION
**Pull request by tom7**
Trying to create a setup where I can draw the visualization. For now it's just plopped down next to the existing UI. Probably no reason to check this in, though it can be disabled with BO_ENABLE_VISUALIZATION macro so that it can live in the current code with minimal invasion.

But I wanted to ask: Any suggestions for the "right" (or at least "good") way to get the current effective divisor and buffer size (post LFOs) in reflect or otherwise?

### CODE REVIEW

**Comment by sophiapoirier** [comment]
Honestly I think this visualization is perfect as-is.

So far as design for reflecting current parameter values in the BOView, the first change I would make is moving from pull to push for the values.  Geometer differs in querying a property, and that the property changes originate from a realtime context, and that combination adds more challenges to designing the data sharing system. But in this case there already is a push mechanism in VSTGUI/DFXGUI the lands at the `BufferOverrideEditor::parameterChanged` override. So I would relay the parameter change notifications from there to BufferOverrideView and react accordingly.  Which probably in BufferOverrideView would simply be a call to `invalid()` (filtered on parameter IDs of interest), and then let the view's `draw` method query the actual current values of the parameters in play.

**Comment by tom7** [comment]
Thanks! With you if just using parameters directly. But (and this is not in the code currently) I think I want to base it on the final computed buffer/divisor (taking into account LFOs for example), not directly from the input parameter values. So like mMinibufferSize and mCurrentForcedBufferSize. Does it make sense to try to write to the view from BufferOverride::updateBuffer, which computes them? I seem to remember there's something complicated there, like they're not even in the same process necessarily.

I think these potentially change constantly (if LFOs are on) so updating solely in response to a parameter change is not enough?

**Comment by sophiapoirier** [comment]
Whoops right, my suggestion only suffices for what is being visualized currently, not what is intended.

So yes, you are remembering correctly that specifically in AU the effect and GUI are not guaranteed to be in the same process (or even address space; once upon a time Logic supported multi-machine processing nodes, though I think that feature got abandoned).  Also effect<->GUI is not always one-to-one (a single effect instance can have more than one GUI instance interfacing with it).  VST2 is not like this and both components will always be in the same address space and the relationship will be one-to-one.

So the first thing I will say is that, if you want to prototype easily and/or don't want to fuss about a requirement that doesn't affect you, you can just get a DfxPlugin pointer from `DfxGuiEditor::dfxgui_GetEffectInstance` and poke away at it.  Or the reverse, call methods on the GUI instance from the effect.  If managing a platform's needs that you can't exactly test sounds annoying, I'm happy to effort-share with this and handle that part of the equation.  But either way, I will also get into those details in a moment...

I think that the first question to answer is whether you want the visualization to literally reflect the realtime "truth" of the effect or if you want it to reflect the idea.  Deriving the data from mMinibufferSize and mCurrentForcedBufferSize would certainly be a version or reflecting the truth live.  The downsides of this, in my opinion, are greater complexity (dealing with data sharing and realtime safety) and that you only see updates while audio is rendering (pause playback and the visualization will ignore your parameter changes).  I actually think it would be more than pushing those internal effect values but would require maintaining some history and be able to share this history in appropriate chunks.  Or I guess technically the GUI could maintain data history, but given that realtime safety and GUI pulling from effect design requirements, it likely will need to tolerate dropped data, which might look weird.  For example, Geometer does this, but with live waveform data changing constantly in discrete chunks, it's fine.  In the case of a stream of historical data, it might look more misleading or confusing if slices of the view were dropped.  The upside is you see what you're hearing live.

The alternative would be to take the collection of relevant parameter values plus effective tempo (whether from parameter or host) and calculate the same stuff that the effect calculates.  This would involve some animation when either LFO depth is above zero.  While this will provide a hint of what you will hear, the downside is that it is not an accurate live correspondence to what you are hearing.  But it is nice that it doesn't freeze when audio stops (though a hybrid solution could be possible to address this).  Also it is much simpler to implement in terms of data sharing and realtime safety (effective tempo would be the only non-parameter bit of data to plumb out of the effect, which can just be a handily lock-free atomic value published through a private property).

If I were the one mucking, I would probably go with the latter, or at least start that route and see whether the non-realtime-matching results are actually off-putting or not.  But the reason for me is that I went through a lot of iterations getting things right with Geometer's threading and data sharing and realtime-safety issues, and often that stuff felt like my job, not how I want DFX stuff to feel. But that's just my experience! But it is tricky.

At first, there were just actually mistakes to correct where Geometer wasn't entirely thread-safe. But after addressing that, I went through iterations to address realtime-safety issues, and then performance issues. One thing that a lot of folks don't realize is that even using `mutex::try_lock` is not realtime safe, because if you succeed in grabbing the mutex, and another non-realtime thread winds up waiting on it, when you release the lock, the scheduler wakes up the waiting non-realtime thread, and that scheduler machinery is an unbounded operation and therefore not realtime-safe. So I switched to an atomic-flag-based spin-lock, which is not optimally performant of course, but it leaves waiting and yielding in our hands without the scheduler, and doing the best option for both platforms felt way too much like work (it would likely be a custom-created mutex substitute based on a Mach semaphore on macOS, and I don't know what on Windows). Next the goal became to make the locking periods as brief as absolutely possible to reduce contention periods when the lock could just spin and burn. Originally, the actual waveform calculations occurred under the lock, so the first thing was to move calculations out and only copy data under the lock. I think I had a couple of iterations of this to improve performance, but it was still a non-trivial amount of data, so my final change was to have two data stores and keep reader and writer pointers to each and do merely a pointer swap while locked.

So anyway, if you went the "realtime truth" route, I would basically copy the design as it has landed in probably the most refined state that it will get in Geometer (unless you're inspired to refine further). There is also other stuff about flagging updates that the GUI polls. It definitely has room for performance improvement, but it's way better than it used to be, entirely realtime-safe, and at least in my opinion good enough.

**Comment by tom7** [comment]
I think this is probably ready to land on main if not release; can you think of anything else we need?

**Comment by sophiapoirier** [comment]
Agreed and it looks so fabulous! I would be inclined to squash everything on this branch to a single commit as it has a lot of invalid between-commit states (very partial work and often didn't properly build on at least one platform), unless you object? (in which case I'd probably still like to do at least some squashing in a few cases)

**Comment by tom7** [comment]
Sure, I don't really have a preference about the commit granularity. Merging it!

**Pull request merged**
