### PR TITLE
copy'n'paste settings on Windows (resolves #7)

### LINKED ISSUE #7: "Copy settings" doesn't do anything on windows
Various stuff is just unimplemented in DfxGuiEditor::copySettings.
We should implement it (probably not hard), but if not, disable this before releasing.

### PR DESCRIPTION
**Pull request by sophiapoirier**
lemme know plz if is worx good 4 u?

### CODE REVIEW

**Comment by tom7** [comment]
Thanks for trying... Alas, it does not work for me!
I added a bunch of tracing to try to figure out what the deal is. The call to setClipboard does succeed, and immediately after that, getClipboard is non-null, but the resulting IDataObject has count of 0. So the paste menu doesn't even show up (query pastability only says no pasta). I can't paste into other apps.

This seems like it could be a problem with vstgui? In the code that converts the clipboard to the win32dataobject when reading:

https://github.com/steinbergmedia/vstgui/blob/9b1ba2e3444d956f74d1e3eb4c02fb034b6f90e5/vstgui/lib/platform/win32/win32datapackage.cpp#L18

the first thing it does is look for a few different formats: text, hdrop, binarydrop (these last two are probably drag-and-drop things?). None succeed. Maybe it vstgui does not support kBinary somehow (this stuff seems to be in win32dragging, and there is some required correspondence between stuff like CF_PRIVATEFIRST and kBinary... I don't get it).

My instinct here would be that the vstgui implication is a lot more complicated than we would need (like it is using OLE APIs, which allow you to do some high-level pasting of objects between apps). It's only a few lines to copy a piece of text to the clipboard using the "regular" win32 API. What if we encoded settings as some base64 text data and wrapped in <dfx-settings></dfx-settings> or something, and then just used simple text-clipboard-setting APIs? This is probably what I would want as a user anyway since then I would know how to save these things using a text editor. (Maybe even better would be if the text were readable/editable, but that'd be more complicated.)

**Comment by sophiapoirier** [comment]
Bleh, honestly I think I am more inclined to file a bug on VSTGUI than do more to work around the issue. I hear you on the text format bonuses, though I only thing that is meaningful when it is a human-readable format, which you suggest, but personally I don't feel motivated enough to work that up (though certainly if you do, have at it).  I see your point about the VSTGUI design and it seems like they sort of shoe-horned drag-and-drop and clipboard concepts together into one and maybe it's not the best match. I have found them to be responsive to filing bugs, though, so feel keen to at least try that and see.

https://github.com/steinbergmedia/vstgui/issues/217

Thank you for trying it out and troubleshooting!

**Comment by sophiapoirier** [comment]
Perhaps wrapping up for release gave me a renewed spurt of motivation... I found a base64 codec buried in VSTGUI which, not exactly human readable, but it is text! I don't have a way to try out win32 APIs, though, whereas I can test this stuff with Mac VST builds, so I just stuck with what I did using the VSTGUI clipboard APIs, but if using base64 seems okay to you and you wanted to replace in direct win32 APIs, whichever way is good with me. I also don't see myself getting the considerably greater amount of motivation to implement meaningful/readable text serialization (AU already serializes state data to XML by default), so that would likely just be if you found yourself interested and motivated towards that.

**Comment by tom7** [comment]
Yes, it works! Thanks for implementing this!
I do think it would be a modest improvement to have some text header/footer like [dfx-settings]a234fh9iey4t98y4[/dfx-settings], because:
 - It makes it clearer to users who might copy settings and then paste them into some other app why their clipboard has weird codes in there
 - More reassuring if you are managing these in a text file or something (?) that you copy-pasted the whole thing
 - It makes the validation step (pastability) faster and less prone to accidental stuff (e.g. I have the whole collected works of shakespeare in my clipboard and right-click on a DFX plugin to do something else).
I can probably implement this pretty easily, but curious whether you see any downsides.

Since the VSGUI APIs are working with text type, using those makes sense to me.

**Comment by tom7** [comment]
Oh hehe, looking back at my previous message I tried to suggest `<dfx-settings></dfx-settings>` but that was stripped out as unknown Markdown, I guess. Perhaps a good reason to use something really simple here that other systems won't try to helpfully interpret.

**Comment by sophiapoirier** [comment]
Okay awesome, thanks for testing! And yeah that header/footer idea makes sense to me and sounds like a good idea. I will merge this now since it is functional, and I think that next step would be a good refinement.

**Pull request merged**
